### ISSUE TITLE
Attached imeges inline.

### ISSUE THREAD

**Issue by hardl0ck** [iMattPro/lightbox#55]
Hello!

phpBB 3.3.8.
plugin 2.0.4

no other plugins for working with attachments installed:
![image](https://user-images.githubusercontent.com/32161522/203248508-ee8db4d5-33c3-45bc-b73a-80bcb5f37d20.png)

Attached images shows in 1 row, like this:
![image](https://user-images.githubusercontent.com/32161522/203247760-2ce1459c-2d06-4c9d-bfec-df26a1e628c3.png)
but i`m want shows it inline, like this:
![image](https://user-images.githubusercontent.com/32161522/203247867-1ee02e7f-f49a-42ba-a1d3-1f6f5d8b4632.png)
in post text all atachments is in one line:
![image](https://user-images.githubusercontent.com/32161522/203248184-b618f758-4c9e-4f08-9767-0997fc1ef697.png)

**Comment by iMattPro** [comment]
phpBB puts attachments on new lines. This extension can't do anything about that.
