### ISSUE TITLE
Overlay model issues when HTML data is returned

### ISSUE THREAD

**Issue by ZMarkC** [iMattPro/lightbox#56]
I have users posting BBCode in this format:

`[URL=https://images.private-domain.com/image/d8f82c8c49.jpg][IMG]https://images.private-domain.com/image/raw/d8f82c8c49.jpg[/IMG][/URL]`

This works fine with the resize feature, but I'm seeing issues where the overlay is trying to load "https://images.private-domain.com/image/d8f82c8c49.jpg"

I assume your code applies the overlay to the first URL due to the presence of ".jpg" 

However, in this case the URL returns a HTML page and I guess the JS code can't do anything with it.

Can you add a timeout to the overlay feature, or some trick to detect HTML data being returned and report an issue or show a link to the page?

Also add an option to disable overlay globally, or per domain whilst keeping the resize feature. This would allow users to click through to the third party site as normal.

**Comment by iMattPro** [comment]
Well when you make it like that, you're saying that whatever is in the URL tag needs to be a clickable link to that URL. So it's all actually behaving as intended in that scenario.

**Comment by ZMarkC** [comment]
I'm not sure I follow.

At the moment, when clicking on a resized image I get this:

![error overlay](https://user-images.githubusercontent.com/18635294/231837945-86ca33c6-8abd-415d-8e29-2d5d5c66d8b5.png)

The lightbox js has requested the wrong data, it loaded the URL part of the bbcode, not the IMG part:

![html request](https://user-images.githubusercontent.com/18635294/231838080-b823d0ba-c650-427f-9160-3066ee5003f4.png)

and hence, it got HTML (correctly so)

The relevant BBcode if you wish to reproduce, is:

`[URL=https://images.pheonix-rising.nl/image/208248f8ab.jpeg?key=pKwFF1u7Z0oQvEgTx4P88NFoeU7AKIfCChxtTEH72ss=][IMG]https://images.pheonix-rising.nl/image/120/208248f8ab.jpeg?key=pKwFF1u7Z0oQvEgTx4P88NFoeU7AKIfCChxtTEH72ss=[/IMG][/URL]`

**Comment by iMattPro** [comment]
Your issue is not reproducible. Those bbcode examples behave as expected, which is Lightbox is disabled on them when they are inside a URL tag. If it's not working for you I suspect you have a style or some other extension that modifies URLs interfering and breaking the intended behavior.

**Comment by ZMarkC** [comment]
I have experimented and discovered the issue only appears when [primlinks](https://github.com/primehalo/primelinks) is enabled.

I have disabled it for now, I was using it to set some links to open in a new tab. Thanks for the help.
