### ISSUE TITLE
Uncaught Twig\Error\LoaderError

### ISSUE THREAD

**Issue by gpraceman** [iMattPro/lightbox#58]
I recently updated my board to 3.3.10 and updated this plugin to2.0.4.  In the ACP, all seems fine.  Yet when I look at the error_log, I see this error.

[12-Jun-2023 17:14:33 UTC] PHP Fatal error:  Uncaught Twig\Error\LoaderError: Looks like you try to load a template outside configured directories (../template/lightbox/css/lightbox.css) in "@vse_lightbox/event/overall_header_head_append.html" at line 2. in /home/derbyt/public_html/vendor/twig/twig/src/Loader/FilesystemLoader.php:291
Stack trace:
#0 /home/derbyt/public_html/vendor/twig/twig/src/Loader/FilesystemLoader.php(211): Twig\Loader\FilesystemLoader->validateName()
#1 /home/derbyt/public_html/phpbb/template/twig/loader.php(135): Twig\Loader\FilesystemLoader->findTemplate()
#2 /home/derbyt/public_html/vendor/twig/twig/src/Loader/FilesystemLoader.php(150): phpbb\template\twig\loader->findTemplate()
#3 /home/derbyt/public_html/phpbb/template/twig/environment.php(328): Twig\Loader\FilesystemLoader->getCacheKey()
#4 /home/derbyt/public_html/cache/production/twig/d2/d2205b92c4a0bfd2e03009e5caeb545c.php(45): phpbb\template\twig\environment->findTemplate()
#5 /home/derbyt/public_html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_e03aa706930a488beb248ee45717ca71->doDisplay()
#6 /home/derbyt/public_html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#7 /home/derbyt/public_html/cache/production/twig/4c/4c15437a6157838e4eecfc3bf27c7e89.php(296): Twig\Template->display()
#8 /home/derbyt/public_html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_9ae6ed2088ac941877cc86984247f755->doDisplay()
#9 /home/derbyt/public_html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#10 /home/derbyt/public_html/cache/production/twig/4a/4af64a00db9fe58d969b933f780ab467.php(44): Twig\Template->display()
#11 /home/derbyt/public_html/vendor/twig/twig/src/Template.php(405): __TwigTemplate_8ce6b19ca405a66ffe96fa60af9eb327->doDisplay()
#12 /home/derbyt/public_html/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#13 /home/derbyt/public_html/vendor/twig/twig/src/Template.php(390): Twig\Template->display()
#14 /home/derbyt/public_html/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render()
#15 /home/derbyt/public_html/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render()
#16 /home/derbyt/public_html/phpbb/template/twig/environment.php(224): Twig\Environment->render()
#17 /home/derbyt/public_html/phpbb/template/twig/environment.php(194): phpbb\template\twig\environment->display_with_assets()
#18 /home/derbyt/public_html/phpbb/template/twig/twig.php(317): phpbb\template\twig\environment->display()
#19 /home/derbyt/public_html/includes/functions.php(4292): phpbb\template\twig\twig->display()
#20 /home/derbyt/public_html/search.php(1365): page_footer()
#21 {main}
  thrown in /home/derbyt/public_html/vendor/twig/twig/src/Loader/FilesystemLoader.php on line 291

**Comment by iMattPro** [comment]
You have to purge your forum's cache.
